= Xây dựng hệ thống với Spring Boot
<xây-dựng-hệ-thống-với-spring-boot>
#include "spring/starter.typ"
#include "spring/mybatis.typ"
#include "spring/cache.typ"
#include "spring/rabbitmq.typ"
#include "spring/elasticsearch.typ"
#include "spring/docker.typ"
#include "spring/elk.typ"
#include "spring/admin.typ"
#include "spring/apollo.typ"
#include "spring/security.typ"
#include "spring/actuator.typ"
#include "spring/seata.typ"
#include "spring/validation.typ"
#include "spring/microservices.typ"
